#!/bin/sh
# Copyright © 2021 Galois, Inc.  All rights reserved.

exec `dirname $0`/do-configure x86_64-unknown-fromager \
    -Dmultilib=false \
    -Dpicocrt=false \
    -Dio-c99-formats=false \
    -Dio-float-exact=false \
    -Dio-long-double=false \
    -Datomic-ungetc=false \
    -Dnewlib-multithread=false \
    -Dnewlib-nano-malloc=false \
    -Dlibm-long-double=false \
    -Dtests=false \
    -Dspecsdir=none \
    -Dhave-alias-attribute=false \
    --prefix $PWD/image \
    "$@"
